package com.myspace.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class obj1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public obj1() {
    }




}